apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform-infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  description: "Platform shared infrastructure project"
  sourceRepos:
    - "https://github.com/<YOUR_GITHUB_USERNAME>/platform-infra.git"
    - https://charts.bitnami.com/bitnami
    - oci://registry-1.docker.io/bitnamicharts
    - https://helm.goharbor.io
    - https://bitnami-labs.github.io/sealed-secrets
    - https://charts.jetstack.io
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://grafana-community.github.io/helm-charts
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
